### ISSUE TITLE
Cannot set properties of undefined (setting 'readingTime')"

### ISSUE THREAD

**Issue by islamzaoui** [lubiah/mdsvex-reading-time#1]
Hello 

I tried to open +page.md page in my svelte-kit project but I got this error when using this plugin `Cannot set properties of undefined (setting 'readingTime')"`
when I remove it then it works fine

you can find my project [here](https://github.com/IslamZaoui/MyBlog)

is there any fix?

**Comment by islamzaoui** [comment]
i also got the same error while building the project
```bash
12:27:48.201 | TypeError: Error while preprocessing /vercel/path0/src/routes/playground/markdown-preview/+page.md - Cannot set properties of undefined (setting 'readingTime')
12:27:48.201 | at file:///vercel/path0/node_modules/.pnpm/mdsvex-reading-time@1.0.4_@types+node@20.12.7_typescript@5.4.5_vite@5.2.10/node_modules/mdsvex-reading-time/dist/mdsvex-reading-time.js:12:32
12:27:48.201 | at wrapped (/vercel/path0/node_modules/.pnpm/mdsvex@0.11.0_svelte@4.2.15/node_modules/mdsvex/dist/main.cjs.js:206:19)
12:27:48.201 | at next (/vercel/path0/node_modules/.pnpm/mdsvex@0.11.0_svelte@4.2.15/node_modules/mdsvex/dist/main.cjs.js:299:28)
12:27:48.201 | at done (/vercel/path0/node_modules/.pnpm/mdsvex@0.11.0_svelte@4.2.15/node_modules/mdsvex/dist/main.cjs.js:236:16)
12:27:48.201 | at then (/vercel/path0/node_modules/.pnpm/mdsvex@0.11.0_svelte@4.2.15/node_modules/mdsvex/dist/main.cjs.js:243:5)
12:27:48.201 | at wrapped (/vercel/path0/node_modules/.pnpm/mdsvex@0.11.0_svelte@4.2.15/node_modules/mdsvex/dist/main.cjs.js:226:9)
12:27:48.201 | at next (/vercel/path0/node_modules/.pnpm/mdsvex@0.11.0_svelte@4.2.15/node_modules/mdsvex/dist/main.cjs.js:299:28)
12:27:48.201 | at done (/vercel/path0/node_modules/.pnpm/mdsvex@0.11.0_svelte@4.2.15/node_modules/mdsvex/dist/main.cjs.js:236:16)
12:27:48.201 | at then (/vercel/path0/node_modules/.pnpm/mdsvex@0.11.0_svelte@4.2.15/node_modules/mdsvex/dist/main.cjs.js:243:5)
12:27:48.201 | at wrapped (/vercel/path0/node_modules/.pnpm/mdsvex@0.11.0_svelte@4.2.15/node_modules/mdsvex/dist/main.cjs.js:226:9)
12:27:48.235 | ELIFECYCLE  Command failed with exit code 1.
12:27:48.253 | Error: Command "pnpm run build" exited with 1
```

**Comment by lubiah** [comment]
@IslamZaoui , hello. Are you still facing the issue

**Comment by islamzaoui** [comment]
@lubiah I removed +page.md from my project and I didn't use it since then

**Comment by lubiah** [comment]
Hello @IslamZaoui , I figured out the issue. The problem is that, there's no frontmatter in that article that's why there was a bug.
If you include a frontmatter in your article, the bug dissapears
